### ISSUE TITLE
Your Fca In NPM Registry Got Taken Down

### ISSUE THREAD

**Issue by JakeAsunto** [HarryWakazaki/Fca-Horizon-Mod#36]
Will you fix it?
Why was it taken down?

**Comment by HarryWakazaki** [comment]
bc some people don't have brain was reported it, i will fix it!

**Comment by CatalizCS** [comment]
> bc some people don't have brain was reported it, i will fix it!

Not a crappy report but because your project itself contains malicious code, not the npmjs and github moderators who intentionally removed it from their platform 😏
![image](https://user-images.githubusercontent.com/36947924/215656775-9ca9b193-204f-49f0-8d2a-5deca95bfbc5.png) And you should learn English again to be able to read these lines, dear

**Comment by HarryWakazaki** [comment]
> > bc some people don't have brain was reported it, i will fix it!
> 
> Not a crappy report but because your project itself contains malicious code, not the npmjs and github moderators who intentionally removed it from their platform 😏 ![image](https://user-images.githubusercontent.com/36947924/215656775-9ca9b193-204f-49f0-8d2a-5deca95bfbc5.png) And you should learn English again to be able to read these lines, dear

like that

**Comment by HarryWakazaki** [comment]
Close

**Comment by BadAimWeeb** [comment]
It's npm (a.k.a GitHub (a.k.a Microsoft)) that makes the final decision, if your package doesn't contain any malicious code then it shouldn't be removed in the first place.

YOU are the one that "don't have brain" here. Learn some English and practice, don't just blindly copy other people's code, and throwing some nonsense stuff and say that you "fixed" it. No you aren't fixing it.

cya.

**Comment by HarryWakazaki** [comment]
> > like this
> 
> It's npm (a.k.a GitHub (a.k.a Microsoft)) that makes the final decision, if your package doesn't contain any malicious code then it shouldn't be removed in the first place.
> 
> YOU are the one that "don't have brain" here. Learn some English and practice, don't just blindly copy other people's code, and throwing some nonsense stuff and say that you "fixed" it. No you aren't fixing it.
> 
> cya.
> 
> (btw yes I'm the author of some of the code in this package, you can compare [my package](https://github.com/fca-unofficial/fca-unofficial) with this package. The author of this package ACTIVELY refuses to acknowledge my authorship.)

fca-disme không hề chỉnh gì liên quan đến hoạt động của gói chính, chỉ chỉnh chuyển data vào JSON rồi ra lại để kháng get threadInfo, cũng bị gắn là malicious code?

**Comment by CatalizCS** [comment]
![image](https://user-images.githubusercontent.com/36947924/217132428-10817bcd-ed2d-4fdf-851b-f76823cac59a.png) @BadAimWeeb look this thing 👀👀

**Comment by JakeAsunto** [comment]
maybe you need to change some faults so it wont be detected as malware
